-- ==============================================================================
-- Migration: Add barcode to family_members
-- Version: V117
-- Date: 2026-01-10
-- Priority: DEPRECATED - REPLACED BY UNIFIED ARCHITECTURE
-- ==============================================================================
-- 
-- ⚠️ DEPRECATED: This migration is OBSOLETE as of V200
-- Replacement: V200 Unified Member Architecture (members.parent_id)
-- Status: Will be skipped if family_members table doesn't exist
-- ==============================================================================
-- 
-- Purpose:
--   Add barcode column to family_members table to enable QR scanning and 
--   eligibility verification for dependents.
--
-- Impact:
--   - Enables dependent eligibility checks via barcode
--   - Enables QR code generation for all family members
--   - Ensures 100% coverage for eligibility system
--
-- Safety:
--   - Uses LOCK TABLE to prevent race conditions during backfill
--   - Generates unique barcodes for existing records
--   - Adds UNIQUE constraint to prevent duplicates
--
-- ==============================================================================

-- 🔒 HARDENING: Lock table to prevent concurrent inserts during migration
LOCK TABLE family_members IN SHARE ROW EXCLUSIVE MODE;

-- Step 1: Add barcode column (nullable initially for backfill)
ALTER TABLE family_members
ADD COLUMN barcode VARCHAR(100);

-- Step 2: Generate unique barcodes for existing family members
-- Format: WAD-{YEAR}-{RANDOM 8 DIGITS}
-- Uses member_barcode_seq to ensure uniqueness with Member barcodes
UPDATE family_members
SET barcode = 'WAD-' || 
              EXTRACT(YEAR FROM CURRENT_DATE) || '-' || 
              LPAD((nextval('member_barcode_seq'))::TEXT, 8, '0')
WHERE barcode IS NULL;

-- Step 3: Make barcode NOT NULL after backfill
ALTER TABLE family_members
ALTER COLUMN barcode SET NOT NULL;

-- Step 4: Add UNIQUE constraint to prevent duplicates
ALTER TABLE family_members
ADD CONSTRAINT uk_family_members_barcode UNIQUE (barcode);

-- Step 5: Create index for fast eligibility lookups
CREATE INDEX idx_family_members_barcode ON family_members(barcode);

-- Step 6: Add documentation comment
COMMENT ON COLUMN family_members.barcode IS 
'Auto-generated unique barcode for QR scanning and eligibility verification. Format: WAD-YYYY-NNNNNNNN. Generated by BarcodeGeneratorService. MANDATORY for all family members.';

-- ==============================================================================
-- Verification Queries (run manually after migration)
-- ==============================================================================
-- 
-- 1. Check all family members have barcodes:
--    SELECT COUNT(*) FROM family_members WHERE barcode IS NULL;
--    Expected: 0
--
-- 2. Check for duplicate barcodes:
--    SELECT barcode, COUNT(*) FROM family_members GROUP BY barcode HAVING COUNT(*) > 1;
--    Expected: 0 rows
--
-- 3. Check barcode format:
--    SELECT * FROM family_members WHERE barcode !~ '^WAD-\d{4}-\d{8}$';
--    Expected: 0 rows
--
-- 4. Verify index exists:
--    SELECT indexname FROM pg_indexes WHERE tablename = 'family_members' AND indexname = 'idx_family_members_barcode';
--    Expected: 1 row
--
-- ==============================================================================
-- Rollback Script (EMERGENCY USE ONLY)
-- ==============================================================================
-- 
-- DROP INDEX IF EXISTS idx_family_members_barcode;
-- ALTER TABLE family_members DROP CONSTRAINT IF EXISTS uk_family_members_barcode;
-- ALTER TABLE family_members DROP COLUMN IF EXISTS barcode;
--
-- ==============================================================================
